# Generated by Django 4.1 on 2022-09-10 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ManyToManyField(to='home.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteAutorizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantePublicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.articulos')),
                ('publica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiantepublicaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Telefono',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='comenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiantepublicaciones'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudianteautorizaciones'),
        ),
    ]
